version: '3'
services:
    frontend:
        build: hc-demo-frontend
        ports:
            - '8080:80'
        links:
            - backend
    backend:
        build: hc-demo-backend
        links:
            - kafka
    generator:
        build: hc-demo-generator
        links:
            - kafka
    kafka:
        image: wurstmeister/kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        links:
            - zookeeper
    zookeeper:
        image: bitnami/zookeeper
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
