version: '3'
services:
    frontend:
        build: hc-demo-frontend
        ports:
            - '8080:80'
        links:
            - api

    api:
        build: hc-demo-backend/hc-demo-api
        links:
            - ignite

    generator:
        build: hc-demo-backend/hc-demo-generator
        links:
            - ignite

    ignite:
        build: hc-demo-backend/hc-demo-ignite-server
