version: '3'
services:
    frontend:
        build: hc-demo-frontend
        ports:
            - '8080:80'
        links:
            - api

    api:
        build: hc-demo-backend/hc-demo-api
        environment:
            - spring_profiles_active=prod
            - loader_batch-size=100000
            - loader_rows-to-be-loaded=200000
        links:
            - ignite

    generator:
        build: hc-demo-backend/hc-demo-generator
        environment:
            - spring_profiles_active=prod
        links:
            - ignite

    ignite:
        build: ignite
