com.gridgain.hcdemo:
  local.ignite.hosts: ignite
  model:
    rows-to-be-loaded: 200000
    batch-size: 200
  influx:
    url: 'http://metrics:8086'
    username: root
    password: root
    database: metrics