# Configuration with execution with Apache Ignite.
spring:
  datasource:
    url: jdbc:ignite:thin://ignite
    username: ignite
    password: ignite
    driver-class-name: org.apache.ignite.IgniteJdbcThinDriver
    initialization-mode: always

spring.jpa.properties.hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  temp.use_jdbc_metadata_defaults: false