CREATE TABLE IF NOT EXISTS APPLICATION (
  SK_ID_CURR INT PRIMARY KEY,                   -- client client_id, add into this table
  TARGET INT,
  NAME_CONTRACT_TYPE VARCHAR(255),
  CODE_GENDER VARCHAR(255),                     -- client
  FLAG_OWN_CAR VARCHAR(255),                    -- client
  FLAG_OWN_REALTY VARCHAR(255),                 -- client
  CNT_CHILDREN INT,                             -- client
  AMT_INCOME_TOTAL DOUBLE,                      -- client
  AMT_CREDIT DOUBLE,
  AMT_ANNUITY DOUBLE,
  AMT_GOODS_PRICE DOUBLE,
  NAME_TYPE_SUITE VARCHAR(255),
  NAME_INCOME_TYPE VARCHAR(255),                -- client
  NAME_EDUCATION_TYPE VARCHAR(255),             -- client
  NAME_FAMILY_STATUS VARCHAR(255),              -- client
  NAME_HOUSING_TYPE VARCHAR(255),               -- client
  REGION_POPULATION_RELATIVE DOUBLE,            -- client
  DAYS_BIRTH INT,                               -- client (calc)
  DAYS_EMPLOYED INT,                            -- client (calc)
  DAYS_REGISTRATION DOUBLE,                     -- client (calc)
  DAYS_ID_PUBLISH INT,                          -- client (calc)
  OWN_CAR_AGE DOUBLE,                           -- client (calc)
  FLAG_MOBIL INT,                               -- client
  FLAG_EMP_PHONE INT,                           -- client
  FLAG_WORK_PHONE INT,                          -- client
  FLAG_CONT_MOBILE INT,                         -- client
  FLAG_PHONE INT,                               -- client
  FLAG_EMAIL INT,                               -- client
  OCCUPATION_TYPE VARCHAR(255),                 -- client
  CNT_FAM_MEMBERS DOUBLE,                       -- client
  REGION_RATING_CLIENT INT,                     -- client
  REGION_RATING_CLIENT_W_CITY INT,              -- client
  WEEKDAY_APPR_PROCESS_START VARCHAR(255),
  HOUR_APPR_PROCESS_START INT,
  REG_REGION_NOT_LIVE_REGION INT,               -- client
  REG_REGION_NOT_WORK_REGION INT,               -- client
  LIVE_REGION_NOT_WORK_REGION INT,              -- client
  REG_CITY_NOT_LIVE_CITY INT,                   -- client
  REG_CITY_NOT_WORK_CITY INT,                   -- client
  LIVE_CITY_NOT_WORK_CITY INT,                  -- client
  ORGANIZATION_TYPE VARCHAR(255),               -- client
  EXT_SOURCE_1 DOUBLE,
  EXT_SOURCE_2 DOUBLE,
  EXT_SOURCE_3 DOUBLE,
  APARTMENTS_AVG DOUBLE,                        -- client
  BASEMENTAREA_AVG DOUBLE,                      -- client
  YEARS_BEGINEXPLUATATION_AVG DOUBLE,           -- client
  YEARS_BUILD_AVG DOUBLE,                       -- client
  COMMONAREA_AVG DOUBLE,                        -- client
  ELEVATORS_AVG DOUBLE,                         -- client
  ENTRANCES_AVG DOUBLE,                         -- client
  FLOORSMAX_AVG DOUBLE,                         -- client
  FLOORSMIN_AVG DOUBLE,                         -- client
  LANDAREA_AVG DOUBLE,                          -- client
  LIVINGAPARTMENTS_AVG DOUBLE,                  -- client
  LIVINGAREA_AVG DOUBLE,                        -- client
  NONLIVINGAPARTMENTS_AVG DOUBLE,               -- client
  NONLIVINGAREA_AVG DOUBLE,                     -- client
  APARTMENTS_MODE DOUBLE,                       -- client
  BASEMENTAREA_MODE DOUBLE,                     -- client
  YEARS_BEGINEXPLUATATION_MODE DOUBLE,          -- client
  YEARS_BUILD_MODE DOUBLE,                      -- client
  COMMONAREA_MODE DOUBLE,                       -- client
  ELEVATORS_MODE DOUBLE,                        -- client
  ENTRANCES_MODE DOUBLE,                        -- client
  FLOORSMAX_MODE DOUBLE,                        -- client
  FLOORSMIN_MODE DOUBLE,                        -- client
  LANDAREA_MODE DOUBLE,                         -- client
  LIVINGAPARTMENTS_MODE DOUBLE,                 -- client
  LIVINGAREA_MODE DOUBLE,                       -- client
  NONLIVINGAPARTMENTS_MODE DOUBLE,              -- client
  NONLIVINGAREA_MODE DOUBLE,                    -- client
  APARTMENTS_MEDI DOUBLE,                       -- client
  BASEMENTAREA_MEDI DOUBLE,                     -- client
  YEARS_BEGINEXPLUATATION_MEDI DOUBLE,          -- client
  YEARS_BUILD_MEDI DOUBLE,                      -- client
  COMMONAREA_MEDI DOUBLE,                       -- client
  ELEVATORS_MEDI DOUBLE,                        -- client
  ENTRANCES_MEDI DOUBLE,                        -- client
  FLOORSMAX_MEDI DOUBLE,                        -- client
  FLOORSMIN_MEDI DOUBLE,                        -- client
  LANDAREA_MEDI DOUBLE,                         -- client
  LIVINGAPARTMENTS_MEDI DOUBLE,                 -- client
  LIVINGAREA_MEDI DOUBLE,                       -- client
  NONLIVINGAPARTMENTS_MEDI DOUBLE,              -- client
  NONLIVINGAREA_MEDI DOUBLE,                    -- client
  FONDKAPREMONT_MODE VARCHAR(255),              -- client
  HOUSETYPE_MODE VARCHAR(255),                  -- client
  TOTALAREA_MODE DOUBLE,                        -- client
  WALLSMATERIAL_MODE VARCHAR(255),              -- client
  EMERGENCYSTATE_MODE VARCHAR(255),             -- client
  OBS_30_CNT_SOCIAL_CIRCLE DOUBLE,              -- client
  DEF_30_CNT_SOCIAL_CIRCLE DOUBLE,              -- client
  OBS_60_CNT_SOCIAL_CIRCLE DOUBLE,              -- client
  DEF_60_CNT_SOCIAL_CIRCLE DOUBLE,              -- client
  DAYS_LAST_PHONE_CHANGE DOUBLE,                -- client
  FLAG_DOCUMENT_2 INT,
  FLAG_DOCUMENT_3 INT,
  FLAG_DOCUMENT_4 INT,
  FLAG_DOCUMENT_5 INT,
  FLAG_DOCUMENT_6 INT,
  FLAG_DOCUMENT_7 INT,
  FLAG_DOCUMENT_8 INT,
  FLAG_DOCUMENT_9 INT,
  FLAG_DOCUMENT_10 INT,
  FLAG_DOCUMENT_11 INT,
  FLAG_DOCUMENT_12 INT,
  FLAG_DOCUMENT_13 INT,
  FLAG_DOCUMENT_14 INT,
  FLAG_DOCUMENT_15 INT,
  FLAG_DOCUMENT_16 INT,
  FLAG_DOCUMENT_17 INT,
  FLAG_DOCUMENT_18 INT,
  FLAG_DOCUMENT_19 INT,
  FLAG_DOCUMENT_20 INT,
  FLAG_DOCUMENT_21 INT,
  AMT_REQ_CREDIT_BUREAU_HOUR DOUBLE,
  AMT_REQ_CREDIT_BUREAU_DAY DOUBLE,
  AMT_REQ_CREDIT_BUREAU_WEEK DOUBLE,
  AMT_REQ_CREDIT_BUREAU_MON DOUBLE,
  AMT_REQ_CREDIT_BUREAU_QRT DOUBLE,
  AMT_REQ_CREDIT_BUREAU_YEAR DOUBLE
);


CREATE TABLE IF NOT EXISTS BUREAU (
  SK_ID_CURR INT,
  SK_ID_BUREAU INT PRIMARY KEY,
  CREDIT_ACTIVE VARCHAR(255),
  CREDIT_CURRENCY VARCHAR(255),
  DAYS_CREDIT INT,
  CREDIT_DAY_OVERDUE INT,
  DAYS_CREDIT_ENDDATE DOUBLE,
  DAYS_ENDDATE_FACT DOUBLE,
  AMT_CREDIT_MAX_OVERDUE DOUBLE,
  CNT_CREDIT_PROLONG INT,
  AMT_CREDIT_SUM DOUBLE,
  AMT_CREDIT_SUM_DEBT DOUBLE,
  AMT_CREDIT_SUM_LIMIT DOUBLE,
  AMT_CREDIT_SUM_OVERDUE DOUBLE,
  CREDIT_TYPE VARCHAR(255),
  DAYS_CREDIT_UPDATE INT,
  AMT_ANNUITY DOUBLE
);

CREATE TABLE IF NOT EXISTS BUREAU_BALANCE (
  ID INT PRIMARY KEY,
  SK_ID_BUREAU INT,
  MONTHS_BALANCE INT,
  STATUS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PREVIOUS_APPLICATION (
  SK_ID_PREV INT PRIMARY KEY,
  SK_ID_CURR INT,
  NAME_CONTRACT_TYPE VARCHAR(255),
  AMT_ANNUITY DOUBLE,
  AMT_APPLICATION DOUBLE,
  AMT_CREDIT DOUBLE,
  AMT_DOWN_PAYMENT DOUBLE,
  AMT_GOODS_PRICE DOUBLE,
  WEEKDAY_APPR_PROCESS_START VARCHAR(255),
  HOUR_APPR_PROCESS_START INT,
  FLAG_LAST_APPL_PER_CONTRACT VARCHAR(255),
  NFLAG_LAST_APPL_IN_DAY INT,
  RATE_DOWN_PAYMENT DOUBLE,
  RATE_INTEREST_PRIMARY DOUBLE,
  RATE_INTEREST_PRIVILEGED DOUBLE,
  NAME_CASH_LOAN_PURPOSE VARCHAR(255),
  NAME_CONTRACT_STATUS VARCHAR(255),
  DAYS_DECISION INT,
  NAME_PAYMENT_TYPE VARCHAR(255),
  CODE_REJECT_REASON VARCHAR(255),
  NAME_TYPE_SUITE VARCHAR(255),
  NAME_CLIENT_TYPE VARCHAR(255),
  NAME_GOODS_CATEGORY VARCHAR(255),
  NAME_PORTFOLIO VARCHAR(255),
  NAME_PRODUCT_TYPE VARCHAR(255),
  CHANNEL_TYPE VARCHAR(255),
  SELLERPLACE_AREA INT,
  NAME_SELLER_INDUSTRY VARCHAR(255),
  CNT_PAYMENT DOUBLE,
  NAME_YIELD_GROUP VARCHAR(255),
  PRODUCT_COMBINATION VARCHAR(255),
  DAYS_FIRST_DRAWING DOUBLE,
  DAYS_FIRST_DUE DOUBLE,
  DAYS_LAST_DUE_1ST_VERSION DOUBLE,
  DAYS_LAST_DUE DOUBLE,
  DAYS_TERMINATION DOUBLE,
  NFLAG_INSURED_ON_APPROVAL DOUBLE
);

CREATE TABLE IF NOT EXISTS POS_CASH_BALANCE (
  ID INT PRIMARY KEY,
  SK_ID_PREV INT,
  SK_ID_CURR INT,
  MONTHS_BALANCE INT,
  CNT_INSTALMENT DOUBLE,
  CNT_INSTALMENT_FUTURE DOUBLE,
  NAME_CONTRACT_STATUS VARCHAR(255),
  SK_DPD INT,
  SK_DPD_DEF INT
);

CREATE TABLE IF NOT EXISTS INSTALLMENTS_PAYMENTS (
  ID INT PRIMARY KEY,
  SK_ID_PREV INT,
  SK_ID_CURR INT,
  NUM_INSTALMENT_VERSION DOUBLE,
  NUM_INSTALMENT_NUMBER INT,
  DAYS_INSTALMENT DOUBLE,
  DAYS_ENTRY_PAYMENT DOUBLE,
  AMT_INSTALMENT DOUBLE,
  AMT_PAYMENT DOUBLE
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD_BALANCE (
  ID INT PRIMARY KEY,
  SK_ID_PREV INT,
  SK_ID_CURR INT,
  MONTHS_BALANCE INT,
  AMT_BALANCE DOUBLE,
  AMT_CREDIT_LIMIT_ACTUAL INT,
  AMT_DRAWINGS_ATM_CURRENT DOUBLE,
  AMT_DRAWINGS_CURRENT DOUBLE,
  AMT_DRAWINGS_OTHER_CURRENT DOUBLE,
  AMT_DRAWINGS_POS_CURRENT DOUBLE,
  AMT_INST_MIN_REGULARITY DOUBLE,
  AMT_PAYMENT_CURRENT DOUBLE,
  AMT_PAYMENT_TOTAL_CURRENT DOUBLE,
  AMT_RECEIVABLE_PRINCIPAL DOUBLE,
  AMT_RECIVABLE DOUBLE,
  AMT_TOTAL_RECEIVABLE DOUBLE,
  CNT_DRAWINGS_ATM_CURRENT DOUBLE,
  CNT_DRAWINGS_CURRENT INT,
  CNT_DRAWINGS_OTHER_CURRENT DOUBLE,
  CNT_DRAWINGS_POS_CURRENT DOUBLE,
  CNT_INSTALMENT_MATURE_CUM DOUBLE,
  NAME_CONTRACT_STATUS VARCHAR(255),
  SK_DPD INT,
  SK_DPD_DEF INT
);